-- CreateTable
CREATE TABLE "regrid_parcels_hendricks_in" (
    "id" BIGSERIAL NOT NULL,
    "ll_uuid" TEXT NOT NULL,
    "geoid" TEXT,
    "parcelnumb" TEXT,
    "parcelnumb_no_formatting" TEXT,
    "state_parcelnumb" TEXT,
    "account_number" TEXT,
    "tax_id" TEXT,
    "alt_parcelnumb1" TEXT,
    "alt_parcelnumb2" TEXT,
    "alt_parcelnumb3" TEXT,
    "usecode" INTEGER,
    "usedesc" TEXT,
    "zoning" TEXT,
    "zoning_description" TEXT,
    "zoning_type" TEXT,
    "zoning_subtype" TEXT,
    "zoning_code_link" TEXT,
    "zoning_id" INTEGER,
    "struct" INTEGER,
    "structno" TEXT,
    "yearbuilt" INTEGER,
    "year_built_effective_date" INTEGER,
    "numstories" INTEGER,
    "numunits" INTEGER,
    "numrooms" INTEGER,
    "num_bath" INTEGER,
    "num_bath_partial" INTEGER,
    "num_bedrooms" INTEGER,
    "direction" TEXT,
    "street" TEXT,
    "suffix" TEXT,
    "city" TEXT,
    "szip" TEXT,
    "szip5" TEXT,
    "mail_house_number" TEXT,
    "mail_street_dir" TEXT,
    "mail_street" TEXT,
    "mail_street_suffix" TEXT,
    "mail_unit" TEXT,
    "mail_city" TEXT,
    "mail_state2" TEXT,
    "mail_zip" TEXT,
    "mail_zip4" TEXT,
    "owner" TEXT,
    "owner2" TEXT,
    "owner3" TEXT,
    "owner4" TEXT,
    "owner5" TEXT,
    "owner6" TEXT,
    "owner7" TEXT,
    "owner8" TEXT,
    "owner9" TEXT,
    "owner10" TEXT,
    "owner11" TEXT,
    "owner12" TEXT,
    "owner13" TEXT,
    "owner14" TEXT,
    "owner15" TEXT,
    "owner16" TEXT,
    "owner17" TEXT,
    "owner18" TEXT,
    "owner19" TEXT,
    "owner20" TEXT,
    "owner21" TEXT,
    "owner22" TEXT,
    "owner23" TEXT,
    "owner24" TEXT,
    "owner25" TEXT,
    "owner26" TEXT,
    "owner27" TEXT,
    "owner28" TEXT,
    "owner29" TEXT,
    "owner30" TEXT,
    "owner31" TEXT,
    "owner32" TEXT,
    "owner33" TEXT,
    "owner34" TEXT,
    "owner35" TEXT,
    "owner36" TEXT,
    "owner37" TEXT,
    "owner38" TEXT,
    "owner39" TEXT,
    "owner40" TEXT,
    "owner41" TEXT,
    "owner42" TEXT,
    "owner43" TEXT,
    "owner44" TEXT,
    "owner45" TEXT,
    "owner46" TEXT,
    "owner47" TEXT,
    "owner48" TEXT,
    "owner49" TEXT,
    "owner50" TEXT,
    "county" TEXT NOT NULL,
    "state2" TEXT NOT NULL,
    "lat" DOUBLE PRECISION NOT NULL,
    "lon" DOUBLE PRECISION NOT NULL,
    "gisacre" DOUBLE PRECISION,
    "ll_gisacre" DOUBLE PRECISION,
    "improvval" INTEGER,
    "landval" INTEGER,
    "parval" INTEGER,
    "agval" INTEGER,
    "saleprice" INTEGER,
    "saledate" TIMESTAMP(3),
    "taxyear" INTEGER,
    "taxamt" INTEGER,
    "last_ownership_transfer_date" TIMESTAMP(3),
    "fema_flood_zone_data_date" TIMESTAMP(3) NOT NULL,
    "cdl_date" INTEGER,
    "reviseddate" TEXT,
    "ll_updated_at" TIMESTAMP(3) NOT NULL,
    "usps_vacancy_date" TIMESTAMP(3),
    "loaddate" TEXT NOT NULL,
    "appraisal_date" TIMESTAMP(3),
    "ll_last_refresh" TIMESTAMP(3) NOT NULL,
    "ll_stack_uuid" TEXT,
    "ll_address_count" INTEGER,
    "qoz_tract" TEXT,
    "census_tract" TEXT,
    "census_block" TEXT,
    "census_blockgroup" TEXT,
    "census_zcta" TEXT,
    "area_building" INTEGER,
    "area_building_definition" TEXT,
    "ll_gissqft" INTEGER,
    "ll_bldg_footprint_sqft" INTEGER,
    "ll_bldg_count" INTEGER,
    "cdl_majority_percent" DOUBLE PRECISION,
    "population_density" DOUBLE PRECISION,
    "population_growth_past_5_years" DOUBLE PRECISION,
    "population_growth_next_5_years" DOUBLE PRECISION,
    "housing_growth_past_5_years" DOUBLE PRECISION,
    "housing_growth_next_5_years" DOUBLE PRECISION,
    "household_income_growth_next_5_years" DOUBLE PRECISION,
    "highest_parcel_elevation" DOUBLE PRECISION,
    "lowest_parcel_elevation" DOUBLE PRECISION,
    "neighborhood_factor" DOUBLE PRECISION,
    "annual_adjustment_factor_impr" DOUBLE PRECISION,
    "parcel_id" TEXT,
    "legaldesc" TEXT,
    "lot_code" TEXT,
    "plat" TEXT,
    "book" TEXT,
    "page" TEXT,
    "subdivision" TEXT,
    "landuse" TEXT,
    "landuse_description" TEXT,
    "neighborhood" TEXT,
    "neighborhood_id" TEXT,
    "rdi" TEXT,
    "usps_vacancy" TEXT,
    "vacancy_reason" TEXT,
    "fema_flood_zone_raw" TEXT,
    "fema_flood_zone_subtype" TEXT,
    "cdl_raw" TEXT,
    "cdl_majority" TEXT,
    "lbcs_activity" INTEGER,
    "lbcs_activity_desc" TEXT,
    "reason_for_change_code" TEXT,
    "prior_av_total_land" INTEGER,
    "prior_av_total_improvements" INTEGER,
    "adjustment_factor_applied" TEXT,
    "anonymity_from_public_records" TEXT,
    "vacant" TEXT,

    CONSTRAINT "regrid_parcels_hendricks_in_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "regrid_parcels_hendricks_in_ll_uuid_key" ON "regrid_parcels_hendricks_in"("ll_uuid");

-- CreateIndex
CREATE INDEX "regrid_parcels_hendricks_in_lat_lon_idx" ON "regrid_parcels_hendricks_in"("lat", "lon");

-- CreateIndex
CREATE INDEX "regrid_parcels_hendricks_in_county_state2_idx" ON "regrid_parcels_hendricks_in"("county", "state2");
