export const env = {
  SUPABASE_URL: process.env.EXPO_PUBLIC_SUPABASE_URL!,
  SUPABASE_ANON_KEY: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY!,
  RAILWAY_API_BASE_URL: process.env.EXPO_PUBLIC_RAILWAY_API_BASE_URL!,
  POSTHOG_KEY: process.env.EXPO_PUBLIC_POSTHOG_KEY!,
  POSTHOG_HOST: process.env.EXPO_PUBLIC_POSTHOG_HOST || "https://app.posthog.com",
  STRIPE_PUBLISHABLE_KEY: process.env.EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY!,
};
