import React, { useState } from 'react';
import { View, Text, TextInput, Pressable, ActivityIndicator } from 'react-native';
import { useAuth } from '../state/auth';

export function LoginScreen() {
  const { login } = useAuth();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  const onLogin = async () => {
    setErr(null);
    setLoading(true);
    try {
      await login(email.trim(), password);
    } catch (e: any) {
      setErr(e?.message || 'Login failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <View style={{ flex: 1, padding: 20, justifyContent: 'center' }}>
      <Text style={{ fontSize: 28, fontWeight: '700' }}>Block Labor</Text>
      <Text style={{ marginTop: 8, opacity: 0.7 }}>Sign in to view today’s jobs and collect payments.</Text>

      <View style={{ marginTop: 24 }}>
        <Text style={{ fontSize: 12, opacity: 0.7, marginBottom: 6 }}>Email</Text>
        <TextInput
          autoCapitalize="none"
          autoCorrect={false}
          keyboardType="email-address"
          value={email}
          onChangeText={setEmail}
          placeholder="you@company.com"
          style={{ borderWidth: 1, borderColor: '#ccc', borderRadius: 12, padding: 12 }}
        />
      </View>

      <View style={{ marginTop: 16 }}>
        <Text style={{ fontSize: 12, opacity: 0.7, marginBottom: 6 }}>Password</Text>
        <TextInput
          secureTextEntry
          value={password}
          onChangeText={setPassword}
          placeholder="••••••••"
          style={{ borderWidth: 1, borderColor: '#ccc', borderRadius: 12, padding: 12 }}
        />
      </View>

      {err ? (
        <Text style={{ marginTop: 12, color: '#b00020' }}>{err}</Text>
      ) : (
        <View style={{ height: 20, marginTop: 12 }} />
      )}

      <Pressable
        onPress={onLogin}
        disabled={loading}
        style={{
          marginTop: 12,
          backgroundColor: '#111',
          padding: 14,
          borderRadius: 14,
          alignItems: 'center',
          opacity: loading ? 0.7 : 1
        }}
      >
        {loading ? <ActivityIndicator color="#fff" /> : <Text style={{ color: '#fff', fontWeight: '600' }}>Sign in</Text>}
      </Pressable>

      <Text style={{ marginTop: 16, opacity: 0.6, fontSize: 12 }}>
        Demo seed accounts are generated by the API seed script. Check the API console output for the labor login.
      </Text>
    </View>
  );
}
